name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install -r requirements.txt
      - run: python -m pip install -e .
      - run: python examples/run_synthetic_experiment.py --n_users 1000 --seed 0 --policyA epsilon_greedy --policyB softmax --horizon 30 --weight_clip 10 --artifacts_dir synthetic_artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: synthetic-experiment
          path: synthetic_artifacts
      - run: pytest
      - run: python -m pip -V
      - run: python -c "import sys; print('OK', sys.version)"
